
version: "3.11"

services:
  app:
    image: finance_app:v1
    build: .
    command: bash -c './wait-for-it.sh db:5432 -t 10 -- python manage.py runserver 0.0.0.0:8000'
    user: root
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
