# Generated by Django 5.1.5 on 2025-02-04 08:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=255)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='source_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='transaction_id', primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('amount', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.DO_NOTHING, to='server.category')),
                ('source', models.ForeignKey(db_column='source_id', on_delete=django.db.models.deletion.DO_NOTHING, to='server.source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
